### ISSUE TITLE
Question: Do you recommend...

### ISSUE THREAD

**Issue by dcworldwide** [nozzlegear/Riddlevox#3]
Hi Josh, I've just read / enjoyed your script tags tutorial which led me here. Just wondering, if you don't recommend Riddlevox for production usage, can you recommend a open source lib of similar functionality that is?

Thanks

**Comment by nozzlegear** [comment]
To be honest, I was never able to find a good one! That was part of the reason I built this little package, just to see how difficult it would be to get something working well. I never used it in production though, I ended up switching to mailing list services ([Drip](https://www.drip.co/) and [ConvertKit](https://convertkit.com)) that had these little popups included.

**Comment by dcworldwide** [comment]
Oh ok. Thanks for sharing those tools, they look promising. I'll read through their docs to see if they'll help me.
